### ISSUE TITLE
Can't use shelly interface

### ISSUE THREAD

**Issue by kloknibor** [yaourdt/tasmota-to-mgos#10]
Hi!

after flashing tasmota I encountered that the dimming did not work correctly so I wanted to move back to mgos. 

From tasmota I went to tasmota minimal, than updated to your intermediate firmware and than used SHDM-2.zip for the shelly dimmer 2. After doing this the hotspot goes online but the webinterface doesn't work.

The only thing it shows is :

![image](https://user-images.githubusercontent.com/10560390/123760720-6a619580-d8c1-11eb-9655-d4af520c5d2a.png)

when clicking the HTML file I get:

![image](https://user-images.githubusercontent.com/10560390/123760762-73eafd80-d8c1-11eb-971b-3d16fddc7b97.png)

**Comment by EdKo66** [comment]
It seems I have almost the same problem, and hope to find a solution.
Had flashed Shelly 2.5 to Tasmota 9.5.0, but it wasn't working for me, so decided to go back with a minimal Tasmota install and now it comes up with a new wifi-network mg-5FD4E3 and then I can find the Shelly IP as 10.42.42.44. 
After entering that in the browser, i get an index page with two items:
(sorry cant make a screenshot atm)
conf0.json
hwifno_struct.json

and that's it. Please don;t tell me the device is dead now

**Comment by iiseppi** [comment]
I had that problem also, I used curl command that is listed in front page to flash shelly firmware.

**Comment by EdKo66** [comment]
Doing that end in:
C:\Users\edwin\Downloads\Shelly>curl -i -F filedata=@./shelly25.zip http://10.42.42.44/update
curl: (55) Send failure: Connection was aborted

**Comment by EdKo66** [comment]
used another firmware and that seems to have flashed okay. LEt's hope ;)

**Comment by EdKo66** [comment]
Seems to be fixed. So far. I can now see a screen appearing. Not there yet

![shelly](https://user-images.githubusercontent.com/7892897/130358044-1e0f01a2-45fc-4a5f-a2bf-0e109c786783.jpg)

**Comment by oskarhart** [comment]
![image](https://user-images.githubusercontent.com/29094333/130766853-49950769-22b7-492c-898c-404d0f71e90a.png)
I get to Mongoose/6.18 and use terminal to try to update and it seams to work but never restarts and just stays at Mongoose/6.18 
![image](https://user-images.githubusercontent.com/29094333/130767340-9f82957c-5af9-41ac-8268-316d7f255cbd.png)

**Comment by arnizzz** [comment]
Hi kloknibor,
I had the same problem. The solution is to press the reset button(5sec) before booting.  And it starts normally. But the problem is it needs to press every time before boots or restarts. But it is possible to do updates.  I returned to tasmota, not perfect but works. And don't need a serial flash.

**Comment by kloknibor** [comment]
I ended up fixing it aswell. I requested support from shelly and they supplied me another .zip which succesfully restored my device.
